# Generated by Django 3.2.25 on 2025-05-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='music.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='music.Song'),
        ),
    ]
