# Generated by Django 3.2.25 on 2025-05-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20250516_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
